name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewers:
    name: Auto Assign Reviewers
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Request Copilot Review
        uses: actions/github-script@v7
        with:
          script: |
            // Request Copilot as a reviewer
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: ['copilot']
            });

            console.log('✅ Copilot has been requested as a reviewer');
