name: Deploy

on:
  push:
    branches:
      - unreleased
  workflow_dispatch:
    inputs:
      deploy_branch:
        description: 'Branch to deploy'
        required: true
        default: 'unreleased'
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/unreleased' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_branch != '')

    steps:
      - name: Set branch variable
        run: |
          echo "DEPLOY_BRANCH=${{ github.event.inputs.deploy_branch || 'unreleased' }}" >> $GITHUB_ENV
        shell: bash

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        env:
          BRANCH: ${{ env.DEPLOY_BRANCH }}
